package com.moonway.dao;

import com.moonway.dto.OrderItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    int insert(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    int insertSelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    OrderItemDO selectByPrimaryKey(Integer id);

    List<OrderItemDO> selectAllItem();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    int updateByPrimaryKeySelective(OrderItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    int updateByPrimaryKey(OrderItemDO record);

    int increaseSales(@Param("id") Integer id,@Param("amount")Integer amount);
}