package com.moonway.dao;

import com.moonway.dto.SequenceInfoDO;

public interface SequenceInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    int insert(SequenceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    int insertSelective(SequenceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    SequenceInfoDO selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    int updateByPrimaryKeySelective(SequenceInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Tue Feb 16 20:59:01 CST 2021
     */
    int updateByPrimaryKey(SequenceInfoDO record);

    SequenceInfoDO getSequenceByName(String name);
}