package com.moonway.dao;

import com.moonway.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    UserPasswordDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_pwd
     *
     * @mbg.generated Mon Feb 08 23:19:00 CST 2021
     */
    int updateByPrimaryKey(UserPasswordDO record);
}