package com.moonway.dataobject;

public class OrderItemDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.title
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.price
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.description
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.sales
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private Integer sales;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.img_url
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.title
     *
     * @return the value of order_item.title
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.title
     *
     * @param title the value for order_item.title
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.price
     *
     * @return the value of order_item.price
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.price
     *
     * @param price the value for order_item.price
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.description
     *
     * @return the value of order_item.description
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.description
     *
     * @param description the value for order_item.description
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.sales
     *
     * @return the value of order_item.sales
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public Integer getSales() {
        return sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.sales
     *
     * @param sales the value for order_item.sales
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setSales(Integer sales) {
        this.sales = sales;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.img_url
     *
     * @return the value of order_item.img_url
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.img_url
     *
     * @param imgUrl the value for order_item.img_url
     *
     * @mbg.generated Sun Feb 14 18:02:31 CST 2021
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}